---
title: "Earthquakes"
author: "Ben Kooi"
date: "27-2-2022"
output: html_document
---

```{r setup, include=FALSE}
library(leaflet)
knitr::opts_chunk$set(echo = TRUE)
```

## Prepare dataset

For this exercise the data of the CORGIS Dataset Project (2016) is used. The data is collected from the United States Geological Survey and contains all kinds of variables off earthquakes all around the world. For more details on the dataset see <https://corgis-edu.github.io/corgis/csv/earthquakes/>.

```{r dataset}
# read the CORGIS Dataset
earthquakes <- read.csv("https://corgis-edu.github.io/corgis/datasets/csv/earthquakes/earthquakes.csv")

# print the structure of the dataset
str(earthquakes)

# select the earthquakes with a magnitude greater than 5
MagGreater5 <- subset(earthquakes, impact.magnitude>5)

```

## Map Earthquakes

This section display a map with earthquakes of magnitude grater then 5.

```{r map}
# make a custom marker
epicenter <- makeIcon("epicenter.svg", iconHeight=50, iconWidth=50)

# generate a map with clustermarkers and a custom icon
leaflet(data = MagGreater5) %>% addTiles() %>%
  addMarkers(~location.longitude, ~location.latitude, popup = ~as.character(location.full), label = ~as.character(impact.magnitude), icon = epicenter, clusterOptions = markerClusterOptions()) 
```


